### ISSUE TITLE
show a simple, positive indication that required signoffs have been achieved

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/balrog#1229]
We hit an issue today where it wasn't clear that signoff requirements hadn't been met. The change in question needed a signoff from `releng` and `relman`, but we had signoffs from `releng` and `releng-relman`.

One thing we can do to help make this more clear is to have a clear, positive indication that the required signoffs have been achieved. Perhaps a progress bar, or checkmarks beside each required signoff?

**Comment by Barry-dE** [comment]
Can I give this a shot?

**Comment by ZeeMonk-pixel** [comment]
I'll like to fix this issue if it can be  assigned to me.  Pls assign to me

**Comment by Barry-dE** [comment]
.take

**Comment by bhearsum** [comment]
Please feel free to work on this issue and open a pull request when ready. Even if someone else ends up fixing it first, working on it would be good experience.

**Comment by Barry-dE** [comment]
Okay, thanks.

**Comment by CREDO23** [comment]
More info about this issue please ? @bhearsum, @gabrielBusta

**Comment by gabrielBusta** [comment]
Oh also, rather than revoking the sign-off, you can set the "when" in the rule far off into the future so the agent won't implement it for a while. Then you can add and revoke to test your changes.

<img width="947" alt="Screenshot 2023-10-10 at 15 55 18" src="https://github.com/mozilla-releng/balrog/assets/10228658/e6d79054-7c99-4c0e-99fe-906f98e261f3">

**Comment by CREDO23** [comment]
Thank for explanation!

**Comment by bhearsum** [comment]
This is fixed by #3016.
